services:
  - type: web
    name: oregonchem-dashboard
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 9.6.7
      - key: VITE_API_URL
        value: https://oregonchem-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDDPGR2sp9iThMLH-ziE-020Fh0mEjL7Z8
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: oregonchem-pe.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: oregonchem-pe
      - key: VITE_GOOGLE_CLOUD_STORAGE_BUCKET
        value: oregonchem-pe.appspot.com
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: 15551474139
      - key: VITE_FIREBASE_APP_ID
        value: 1:15551474139:web:8b5b5df892bbab8e9f1530
      - key: VITE_APP_NAME
        value: OregonChem Dashboard
      - key: VITE_APP_VERSION
        value: 1.0.0
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      branches:
        only:
          - main
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 50 